version: '3.1'

services:
  app:
    container_name: full_app
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - booksdb-mysql
    networks:
      - fullstack

  booksdb-mysql:
    image: mysql:latest
    container_name: booksdb_db_mysql
    ports:
    - 3306:3306
    restart: on-failure
    environment:
      - MYSQL_ROOT_HOST=booksdb-mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=booksdb
    networks:
      - fullstack
    volumes:
      - database_mysql:/var/lib/mysql

volumes:
  api:
  database_mysql:

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge