version: '3.1'

services:
  app:
    container_name: full_app
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - booksdb_db_mysql
    networks:
      - fullstack

  booksdb_db_mysql:
    image: mysql:latest
    container_name: booksdb_db_mysql
    ports:
    - 3307:3306
    restart: on-failure
    environment:
      - MYSQL_USER=pavel
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=Mysql&paha100688
      - MYSQL_DATABASE=book_test
    networks:
      - fullstack
    volumes:
      - booksdb_db_mysql:/var/lib/mysql

volumes:
  api:
  booksdb_db_mysql:

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge